//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidencyMATCH
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    
    public partial class Doctor
    {
        public int DoctorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AlmaMater { get; set; }
    
        public virtual DoctorPreference DoctorPreference { get; set; }
    }
}
