//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidencyMATCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class HospitalPreference
    {
        public int HospitalID { get; set; }
        public int NumberOfOpenings { get; set; }
        public int ChoiceDoctor1 { get; set; }
        public Nullable<int> ChoiceDoctor2 { get; set; }
        public Nullable<int> ChoiceDoctor3 { get; set; }
        public Nullable<int> ChoiceDoctor4 { get; set; }
        public Nullable<int> ChoiceDoctor5 { get; set; }
    
        public virtual Hospital Hospital { get; set; }
    }
}
