//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResidencyMATCH
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        public int HospitalID { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
    
        public virtual HospitalPreference HospitalPreference { get; set; }
    }
}
